import type { LevelDef } from './types.ts';

// Design notes on the shared mechanic used across several levels:
//
// Hazard tiles ('X') zap the player back to the level's start if stepped
// onto one tile at a time via h/j/k/l. "Jump" motions - 0 $ gg G w b e -
// move directly to a destination without occupying the tiles in between,
// so they sail over hazards safely. This mirrors real Vim: hjkl walk the
// cursor one cell at a time, while 0/$/gg/G/w/b/e are absolute or
// word-relative jumps that don't "pass through" every intervening cell.
//
// Pit tiles ('~') are simply impassable to step motions; word motions
// (w/b/e) can leap over them because word boundaries are computed
// independently of the tiles physically in between - just like Vim skips
// over punctuation/whitespace when hopping between words.

export const LEVELS: LevelDef[] = [
  {
    id: 1,
    title: 'First Steps',
    unlocks: ['h', 'j', 'k', 'l'],
    hint: 'Use h (left) j (down) k (up) l (right) to snake your way to the goal G.',
    grid: [
      '###########',
      '#@........#',
      '#########.#',
      '#.........#',
      '#.#########',
      '#.........#',
      '#########.#',
      '#........G#',
      '###########',
    ],
  },
  {
    id: 2,
    title: 'Line Endings',
    unlocks: ['0', '$'],
    hint: 'Hazard tiles (X) zap you if you walk into them. Press 0 to jump to the start of the row, or $ to jump to its end - jumps sail clean over hazards.',
    grid: [
      '###########',
      '#@.XXXXX..#',
      '#########.#',
      '#..XXXXX..#',
      '#.#########',
      '#..XXXXX..#',
      '#########.#',
      '#G.XXXXX..#',
      '###########',
    ],
  },
  {
    id: 3,
    title: 'Word Hops',
    unlocks: ['w', 'b', 'e'],
    hint: 'Pits (~) block h/j/k/l. Press w to jump to the start of the next word, b for the previous word, e for the end of a word - words leap clean over pits.',
    grid: [
      '###################',
      '#@..~~...~~...~~.G#',
      '###################',
    ],
  },
  {
    id: 4,
    title: 'Top and Bottom',
    unlocks: ['gg', 'G'],
    hint: 'Press G to drop straight to the bottom of a shaft, or gg to jump straight to the top - both sail past the hazards in between.',
    grid: [
      '#########',
      '##@###G##',
      '##X###X##',
      '##X###X##',
      '##X###X##',
      '##X###X##',
      '##X###X##',
      '##X###X##',
      '##.....##',
      '#########',
    ],
  },
  {
    id: 5,
    title: 'Clear the Rubble',
    unlocks: ['dd'],
    hint: 'The goal is buried under rubble (O). Stand on it and press dd (twice) to clear it and win.',
    grid: [
      '###########',
      '#@........#',
      '#########.#',
      '#.........#',
      '#.#########',
      '#.........#',
      '#########.#',
      '#........O#',
      '###########',
    ],
  },
  {
    id: 6,
    title: 'Fetch and Place',
    unlocks: ['yy', 'p'],
    hint: 'Stand on the key (K) and press yy (twice) to pick it up. Walk next to the door (D) and press p to place the key and open it.',
    grid: [
      '###########',
      '#@..K.....#',
      '#########D#',
      '#........G#',
      '###########',
    ],
  },
  {
    id: 7,
    title: 'Combined Trial',
    unlocks: [],
    hint: 'Everything so far: hop the pits with w/e, jump the hazard row with 0, then clear the rubble with dd.',
    grid: [
      '###########',
      '#@~~.~~...#',
      '#########.#',
      '#..XXXXX..#',
      '#.#########',
      '#........O#',
      '###########',
    ],
  },
  {
    id: 8,
    title: 'The Gauntlet',
    unlocks: [],
    hint: 'Drop the shaft with G, fetch the key with yy, and place it with p to open the door.',
    grid: [
      '#########',
      '####@####',
      '####X####',
      '####X####',
      '#.......#',
      '#.K.....#',
      '####D####',
      '####G####',
      '#########',
    ],
  },
  {
    id: 9,
    title: 'Find Files',
    unlocks: ['ff'],
    hint: 'The goal is sealed behind walls with no door - the only way in is knowing its name. Press <space>ff to open the finder, type part of a filename to narrow the list, and Enter to warp straight to it. A few similarly-named files are scattered around as decoys.',
    grid: [
      '#################',
      '#@..............#',
      '#...~~...~~..~~.#',
      '#...F...........#',
      '#..~~~....~~~...#',
      '#.......F.....#.#',
      '#...........F#G##',
      '#.............#.#',
      '#################',
    ],
    files: [
      { name: 'utils.ts', pos: { x: 4, y: 3 }, icon: '🔧' },
      { name: 'router.ts', pos: { x: 8, y: 5 }, icon: '🔗' },
      { name: 'config.ts', pos: { x: 12, y: 6 }, icon: '⚙️' },
      { name: 'index.ts', pos: { x: 14, y: 6 }, icon: '⭐' },
    ],
  },

  // Levels 10-17: every command from here on is already known - what
  // changes is what those same commands can *do*. Two permanent
  // upgrades (see AbilityId in types.ts) are granted along the way,
  // each changing the behavior of existing motions rather than adding a
  // new key to learn - Far Jump lets jumps (0 $ gg G w b e) cross a
  // chasm ('C') the same way they already cross a pit; Phase lets
  // h/j/k/l themselves pass straight through a phase wall ('P'), the
  // one upgrade that changes *walking*, not just jumping. Both are
  // permanent and level-independent once granted - including when
  // revisiting an earlier level (see GameController.recomputeUnlocked
  // and the level-select screen in main.ts), which is what makes level
  // 10's two dormant, sealed side-shafts worth a second visit later.
  {
    id: 10,
    title: 'Deeper In',
    unlocks: [],
    hint: "Nothing new to learn here - just a bigger version of everything so far, back to back: a hazard row, a pit row, then a key and door. Notice the two sealed shafts branching off the start, sitting behind a chasm and a wall that don't look like anything you can cross yet. They aren't, not from here - remember this level. You'll be able to come back for them.",
    grid: [
      '#####################',
      '#@..................#',
      '#.XXXXXXXXXXX.##C##P#',
      '#############.##!##!#',
      '#.~~~~~~~~~~~.#######',
      '#.###################',
      '#...K.....D...#######',
      '#############.#######',
      '#............G#######',
      '#####################',
    ],
  },
  {
    id: 11,
    title: 'Far Jump',
    unlocks: [],
    grantsAbility: 'farjump',
    hint: 'One more full lap with what you already know - hazards, a pit, a key and door - before this one hands you something new.',
    grid: [
      '#################',
      '#@..............#',
      '#.XXXXXXXXXXXXX.#',
      '###############.#',
      '#.~~~~~~~~~~~~~.#',
      '#.###############',
      '#.XXXXXXXXXXXXX.#',
      '###############.#',
      '#....D.....K....#',
      '#.###############',
      '#G..............#',
      '#################',
    ],
  },
  {
    id: 12,
    title: 'The Chasm',
    unlocks: [],
    hint: "Chasms ('C') used to be solid walls to every motion. Far Jump changes that: 0 $ gg G w b e now cross a chasm exactly the way they've always crossed a pit. h/j/k/l still can't - some things only a real jump reaches.",
    grid: [
      '###############',
      '#@............#',
      '#.CCCCCCCCCCC.#',
      '#############.#',
      '#.CCCCCCCCCCC.#',
      '#.#############',
      '#.~~~~~~~~~~~.#',
      '#############.#',
      '#............G#',
      '###############',
    ],
  },
  {
    id: 13,
    title: 'Cross-Reference',
    unlocks: [],
    hint: "No chasm, no hazard, nothing to jump - on purpose. <space>ff doesn't care what's between you and a file, only its name, so it never needed a gauntlet in front of it to prove that. Walk past the two decoys first if you want their icons to mean something in the list, then warp straight into the vault from wherever you're standing.",
    grid: [
      '#################',
      '#@..............#',
      '#...............#',
      '#...F...........#',
      '#...............#',
      '#..........F....#',
      '#...............#',
      '#.......#.......#',
      '########G########',
      '#################',
    ],
    files: [
      { name: 'utils.ts', pos: { x: 4, y: 3 }, icon: '🔧' },
      { name: 'notes.ts', pos: { x: 11, y: 5 }, icon: '📝' },
      { name: 'vault.ts', pos: { x: 8, y: 8 }, icon: '🔒' },
    ],
  },
  {
    id: 14,
    title: 'Phase',
    unlocks: [],
    grantsAbility: 'phase',
    hint: 'A pit, a key and door, a hazard row - nothing here needs what this level is about to hand you. Play it straight, and see what comes after.',
    grid: [
      '#################',
      '#@..............#',
      '#.~~~~~~~~~~~~~.#',
      '###############.#',
      '#.....D.....K...#',
      '#.###############',
      '#.XXXXXXXXXXXXX.#',
      '###############.#',
      '#..............G#',
      '#################',
    ],
  },
  {
    id: 15,
    title: 'Through the Wall',
    unlocks: [],
    hint: "Every one of these connecting doorways is a phase wall ('P'), not open floor - before Phase, this level has no route through at all, not even a jump could help. Now h/j/k/l just... keep going. That's the whole ability: existing motions, no longer stopped by something that used to be solid.",
    grid: [
      '###############',
      '#@............#',
      '#############P#',
      '#.............#',
      '#P#############',
      '#.............#',
      '#############P#',
      '#............G#',
      '###############',
    ],
  },
  {
    id: 16,
    title: 'Compound Interest',
    unlocks: [],
    hint: 'Both upgrades, in the same level: chasms to cross with a jump, phase walls to walk straight through, in whatever order you reach them. Neither one substitutes for the other.',
    grid: [
      '#################',
      '#@..............#',
      '#.CCCCCCCCCCCCC.#',
      '###############P#',
      '#.XXXXXXXXXXXXX.#',
      '#.###############',
      '#.CCCCCCCCCCCCC.#',
      '###############P#',
      '#.....D.....K...#',
      '#.###############',
      '#..............G#',
      '#################',
    ],
  },
  {
    id: 17,
    title: 'The Grid',
    unlocks: ['count'],
    hint: "Everything at once, and bigger: a hazard row, a pit, a phase wall, a chasm, a key and door, then a sealed vault only <space>ff opens - two decoys included. Last tip, now that you've reached the end: a number before a motion repeats it, e.g. 3l moves right three tiles, 5j drops five rows in one press. And if you remember two dormant shafts from early on (Deeper In) - you have everything you need for them now. Nothing's stopping you from going back.",
    grid: [
      '###################',
      '#@................#',
      '#.XXXXXXXXXXXXXXX.#',
      '#################.#',
      '#.~~~~~~~~~~~~~~~.#',
      '#P#################',
      '#.CCCCCCCCCCCCCCC.#',
      '#################.#',
      '#....D.......K....#',
      '#.#################',
      '#...F.........F...#',
      '#......##G##......#',
      '###################',
    ],
    files: [
      { name: 'draft.ts', pos: { x: 4, y: 10 }, icon: '📄' },
      { name: 'grid.ts', pos: { x: 14, y: 10 }, icon: '📦' },
      { name: 'exit.ts', pos: { x: 9, y: 11 }, icon: '🚪' },
    ],
  },
];
